AWSTemplateFormatVersion: '2010-09-09'
Description: Simple S3 bucket via CloudFormation (GitHub Actions demo)

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket to create
    MinLength: 3

Resources:
  DemoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  BucketNameOutput:
    Description: Name of the created bucket
    Value: !Ref DemoBucket
